import { Event } from '@/types';

export const EVENTS: Event[] = [
  {
    id: '1',
    title: 'Grand Masters Invitational 2024',
    category: 'Gaming & Esports',
    image: 'https://images.unsplash.com/photo-1538481143235-e0cf3ee39f47?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Close up of a high-end gaming setup with neon components in a dark minimalist room, cinematic lighting',
    time: 'Starts 10:00 PM',
    isLive: true,
    viewers: 4200,
    featured: true,
  },
  {
    id: '2',
    title: 'Synthesizer Masterclass: Level 2',
    category: 'Music Production',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Deep blue music studio with high-end synthesizers and soft ambient atmospheric lighting',
    time: 'Tomorrow, 6:00 PM',
    isLive: false,
  },
  {
    id: '3',
    title: 'AI Ethics & The Future of Dev',
    category: 'Technology',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Lines of glowing green code on a dark monitor, shallow depth of field, futuristic tech aesthetic',
    time: 'Ends in 45m',
    isLive: true,
    viewers: 2100,
    featured: true,
  },
  {
    id: '4',
    title: 'Midnight Jazz: Solo Performance',
    category: 'Live Sessions',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Musician playing an electric guitar under cinematic spotlights, moody shadows and smoke',
    time: 'Nov 24, 9:00 PM',
    isLive: false,
  },
  {
    id: '5',
    title: 'Minimalist UI Design Workshop',
    category: 'Workshops',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Abstract cinematic visual with Workshops theme, high contrast lighting and deep shadows',
    time: 'Starts 2h',
    isLive: true,
    viewers: 1800,
  },
  {
    id: '6',
    title: 'Digital Illustration Live',
    category: 'Creative',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Artist drawing on digital tablet with stylus under professional lighting',
    time: 'Monday, 10 AM',
    isLive: false,
  },
  {
    id: '7',
    title: 'Electronic Beats Live',
    category: 'Music',
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'DJ performing at electronic music festival with vibrant stage lighting',
    time: 'Tonight, 11 PM',
    isLive: true,
    viewers: 3400,
  },
  {
    id: '8',
    title: 'Cloud Architecture Q&A',
    category: 'Tech',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Data center with glowing servers and network connections',
    time: 'Dec 1, 3:00 PM',
    isLive: false,
  },
  {
    id: '9',
    title: 'Speedrun Marathon',
    category: 'Gaming',
    image: 'https://images.unsplash.com/photo-1511882150382-421b4717cf44?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Multiple gaming monitors showing speedrun gameplay',
    time: 'Starts 30m',
    isLive: true,
    viewers: 5600,
    featured: true,
  },
  {
    id: '10',
    title: 'React Performance 101',
    category: 'Workshops',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Developer typing code on mechanical keyboard with dual monitors',
    time: 'Tuesday, 4:00 PM',
    isLive: false,
  },
  {
    id: '11',
    title: 'Cinematography Basics',
    category: 'Creative',
    image: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Film camera on tripod with cinematic bokeh background',
    time: 'Dec 5, 2:00 PM',
    isLive: false,
  },
  {
    id: '12',
    title: 'Final Boss Challenge',
    category: 'Gaming',
    image: 'https://images.unsplash.com/photo-1538481143235-e0cf3ee39f47?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Epic final boss battle scene with dramatic lighting',
    time: 'In progress',
    isLive: true,
    viewers: 4900,
  },
  {
    id: '13',
    title: 'Acoustic Sunset Sets',
    category: 'Music',
    image: 'https://images.unsplash.com/photo-1514925849778-d3c96e69dd60?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Acoustic guitarist performing during sunset with warm golden lighting',
    time: 'Next Sunday',
    isLive: false,
  },
  {
    id: '14',
    title: 'The Rust Revolution',
    category: 'Tech',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Rust programming language presentation screen',
    time: 'Friday, 8:00 PM',
    isLive: false,
  },
  {
    id: '15',
    title: 'Productivity Systems Mastery',
    category: 'Workshops',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Organized workspace with notebook and planning materials',
    time: 'Dec 10, 10:00 AM',
    isLive: false,
  },
];

export const CATEGORIES = ['All Events', 'Music', 'Tech', 'Gaming', 'Workshops', 'Creative'] as const;

export const SORT_OPTIONS = [
  { value: 'popular', label: 'Sort by: Popular' },
  { value: 'newest', label: 'Sort by: Newest' },
  { value: 'upcoming', label: 'Sort by: Upcoming' },
];

