import { Event } from '@/types';

export const EVENTS: Event[] = [
  {
    id: '1',
    title: 'Grand Masters Invitational 2024',
    category: 'Gaming & Esports',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDjcS68UoduMiAUxvUW-Emuo4P0JhZN2xu0Moe95r3qyOJOX1wuqc8LijRnB5rCdpr2zk6gmoiGpnK_4e9dwGeDhbfQkOdIBE-DIBoZrK8vazfdvFaTrkwXF8r2RDdOY48Bhl4k7LwEaijuhdYCP94zRoQjgMT7n474VIPcHKIB3E8CgW-zEYUYgjsx7zCFEtqUt97TXmhE1DQx0usG1twXHnZ7l4w95n2UOk_iESDcvEoBd8_nuNFzMY9-nNllEW8LmnHC30s4fnA',
    imageAlt: 'High-end gaming setup with neon components in a dark minimalist room',
    time: 'Starts 10:00 PM',
    isLive: true, viewers: 4200, featured: true,
    streamer: 'ProGamer_X', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ProGamer',
    videoId: 'jfKfPfyJRdk',
    description: 'The Grand Masters Invitational 2024 is the most prestigious esports tournament of the year. Top 16 teams from across the globe compete for a $500,000 prize pool. Featuring live commentary, expert analysis, and behind-the-scenes player cams. This is the event that defines champions.',
    tags: ['Esports', 'Gaming', 'Tournament', 'Live'], likes: 3240,
  },
  {
    id: '2',
    title: 'Synthesizer Masterclass: Level 2',
    category: 'Music Production',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBNKCly-dQo8zsq1YaMCiAtWgqo6Bs-aBIkxYReyg_nn7akVnq9g5_JwNbGFrVMhEcWU-p8BT_kRu-gKMmEbGszmEcMDU_VKCc2CRvmYDjL4v_V2HoKmguH8kHoOxHEGmbL7wdfBK8tawN_yz8zEv-8G2bIhSbdHP_q831oSZQMHa4TiAMRy4YWJHzyJZNWVCF04QmmOm2J9MHh9Wo4U2TrYWLO3Raoq9hu8F4emjIkLXHX_1teYBz-j3Pbn8-Zo0ZhVTFFL7X91sM',
    imageAlt: 'Deep blue music studio with high-end synthesizers',
    time: 'Tomorrow, 6:00 PM',
    isLive: false,
    streamer: 'SynthWave_Studio', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SynthWave',
    videoId: 'DubKbIh4jEU',
    description: 'Join award-winning producer Alex Rivera for an advanced synthesizer masterclass. Learn FM synthesis, wavetable design, modular patching techniques, and how to craft signature sounds used in modern electronic music.',
    tags: ['Music', 'Production', 'Synthesizer', 'Workshop'], likes: 1850,
  },
  {
    id: '3',
    title: 'AI Ethics & The Future of Dev',
    category: 'Technology',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAWSOdLqhDiO8qbiKLsd7RQK8xA7dp_vvBEQvjT8GcwiADJ-FPA6Cz59QgufSWOWBmf3W1GRGVSxBbo2BTQfOKi4iAIJwpnzh1NdNQ0bMRiUL5ahBo2ZelntAQ7lULu5vHgdA7qMruTQjcJe6RXhrq0m5CHSObvGRzkvFfHnrQzBxxe0Xt0vRkUoNsjzvPNoDhDxn3zPiu8uWfCH2aGUmoD94KMg6MuTzzuqCyRxXpdSDMTCCyxSNUvZaKDFut84gqiyGwm-141NZY',
    imageAlt: 'Lines of glowing green code on a dark monitor',
    time: 'Ends in 45m',
    isLive: true, viewers: 2100, featured: true,
    streamer: 'DevEthics_Lab', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DevEthics',
    videoId: 'aircAruvnKk',
    description: 'A panel discussion with leading AI researchers exploring the moral responsibilities of developers in the age of generative AI. Topics include bias in ML models, responsible deployment, and the future job landscape for software engineers.',
    tags: ['AI', 'Ethics', 'Technology', 'Panel'], likes: 2100,
  },
  {
    id: '4',
    title: 'Midnight Jazz: Solo Performance',
    category: 'Live Sessions',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAaUAXMIXvomr9YqrdRRNFqt3IkT67kVWOwdyIYSh3hTpCfs1dvN5j6UnHgqI05gYE2tgtEBhe5Wl8qxvFVMEQuZinc5wVcIyoC8O6LkJIsOXRGfnGRdEtVPXWouHxtuP5EIFzH20nJyrMnMSrKg0Il2VhcXEVEcxQyeeVsz1gjXLc7vKfXtr_Csdlgnd5u3Vnv537w4odTqR2gFaRQMbVDEJONQg6QUU1rbDhntDmn1di2rqAeRm4jmW3faycjG9SlMa1WU3C7ma4',
    imageAlt: 'Musician playing electric guitar under cinematic spotlights',
    time: 'Nov 24, 9:00 PM',
    isLive: false,
    streamer: 'JazzMaster_VII', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=JazzMaster',
    videoId: 'wj_VEYgOzUA',
    description: 'Marcus Bellini performs an intimate solo jazz set recorded live from the Blue Note Studio, NYC. An evening of improvisational brilliance blending bebop, fusion, and contemporary jazz. Pure musical expression with no boundaries.',
    tags: ['Jazz', 'Music', 'Live', 'Performance'], likes: 980,
  },
  {
    id: '5',
    title: 'Minimalist UI Design Workshop',
    category: 'Workshops',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDjcS68UoduMiAUxvUW-Emuo4P0JhZN2xu0Moe95r3qyOJOX1wuqc8LijRnB5rCdpr2zk6gmoiGpnK_4e9dwGeDhbfQkOdIBE-DIBoZrK8vazfdvFaTrkwXF8r2RDdOY48Bhl4k7LwEaijuhdYCP94zRoQjgMT7n474VIPcHKIB3E8CgW-zEYUYgjsx7zCFEtqUt97TXmhE1DQx0usG1twXHnZ7l4w95n2UOk_iESDcvEoBd8_nuNFzMY9-nNllEW8LmnHC30s4fnA',
    imageAlt: 'Abstract visual with Workshops theme',
    time: 'Starts 2h',
    isLive: true, viewers: 1800,
    streamer: 'DesignWithMe', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DesignWithMe',
    videoId: 'c9Wg6Cb_YlU',
    description: 'Master the art of doing more with less. This live workshop covers whitespace mastery, typographic hierarchy, color theory for minimal palettes, and building component systems in Figma. Ideal for intermediate designers.',
    tags: ['Design', 'UI/UX', 'Figma', 'Workshop'], likes: 1420,
  },
  {
    id: '6',
    title: 'Digital Illustration Live',
    category: 'Creative',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Artist drawing on digital tablet with stylus',
    time: 'Monday, 10 AM',
    isLive: false,
    streamer: 'ArtByNova', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ArtByNova',
    videoId: 'ZQLlDvEiQg4',
    description: 'Watch professional illustrator Nova create a complete character concept from sketch to final render in Procreate. Full workflow: thumbnail sketching, line art, coloring, texturing, and lighting — with commentary on her creative process.',
    tags: ['Illustration', 'Art', 'Procreate', 'Creative'], likes: 760,
  },
  {
    id: '7',
    title: 'Electronic Beats Live',
    category: 'Music',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAWSOdLqhDiO8qbiKLsd7RQK8xA7dp_vvBEQvjT8GcwiADJ-FPA6Cz59QgufSWOWBmf3W1GRGVSxBbo2BTQfOKi4iAIJwpnzh1NdNQ0bMRiUL5ahBo2ZelntAQ7lULu5vHgdA7qMruTQjcJe6RXhrq0m5CHSObvGRzkvFfHnrQzBxxe0Xt0vRkUoNsjzvPNoDhDxn3zPiu8uWfCH2aGUmoD94KMg6MuTzzuqCyRxXpdSDMTCCyxSNUvZaKDFut84gqiyGwm-141NZY',
    imageAlt: 'DJ performing at electronic music festival',
    time: 'Tonight, 11 PM',
    isLive: true, viewers: 3400,
    streamer: 'DJ_Bassline', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DJBassline',
    videoId: 'oFRbZJXjWIA',
    description: 'DJ Bassline takes the virtual stage for an uninterrupted 3-hour electronic music marathon. Featuring original tracks, bootleg remixes, and surprise collaborations. Genres spanning techno, house, drum & bass, and ambient electronic.',
    tags: ['EDM', 'DJ', 'Festival', 'Live'], likes: 4100,
  },
  {
    id: '8',
    title: 'Cloud Architecture Q&A',
    category: 'Tech',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Data center with glowing servers',
    time: 'Dec 1, 3:00 PM',
    isLive: false,
    streamer: 'CloudGuru_Dev', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CloudGuru',
    videoId: 'M988_fsOSWo',
    description: 'Senior engineers from AWS and GCP answer your most pressing cloud architecture questions. Multi-region deployments, cost optimization, Kubernetes at scale, edge computing, and serverless patterns.',
    tags: ['Cloud', 'AWS', 'Kubernetes', 'Tech'], likes: 540,
  },
  {
    id: '9',
    title: 'Speedrun Marathon',
    category: 'Gaming',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAaUAXMIXvomr9YqrdRRNFqt3IkT67kVWOwdyIYSh3hTpCfs1dvN5j6UnHgqI05gYE2tgtEBhe5Wl8qxvFVMEQuZinc5wVcIyoC8O6LkJIsOXRGfnGRdEtVPXWouHxtuP5EIFzH20nJyrMnMSrKg0Il2VhcXEVEcxQyeeVsz1gjXLc7vKfXtr_Csdlgnd5u3Vnv537w4odTqR2gFaRQMbVDEJONQg6QUU1rbDhntDmn1di2rqAeRm4jmW3faycjG9SlMa1WU3C7ma4',
    imageAlt: 'Multiple gaming monitors showing speedrun gameplay',
    time: 'Starts 30m',
    isLive: true, viewers: 5600, featured: true,
    streamer: 'SpeedDemon99', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SpeedDemon',
    videoId: 'jfKfPfyJRdk',
    description: '24-hour charity speedrun marathon featuring world-record holders across 30 classic and modern titles. Zelda BOTW any%, Dark Souls glitchless, Celeste all hearts. All proceeds go to Games for Good.',
    tags: ['Speedrun', 'Charity', 'Gaming', 'Marathon'], likes: 6700,
  },
  {
    id: '10',
    title: 'React Performance 101',
    category: 'Workshops',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Developer typing code on mechanical keyboard',
    time: 'Tuesday, 4:00 PM',
    isLive: false,
    streamer: 'ReactMaster_Pro', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ReactMaster',
    videoId: 'wIyHSOugGGw',
    description: 'Comprehensive workshop on React performance: React.memo, useMemo, useCallback, React Compiler, Suspense boundaries, virtual scrolling, code splitting, and profiling with real-world production examples.',
    tags: ['React', 'Performance', 'JavaScript', 'Workshop'], likes: 2890,
  },
  {
    id: '11',
    title: 'Cinematography Basics',
    category: 'Creative',
    image: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Film camera on tripod with cinematic bokeh',
    time: 'Dec 5, 2:00 PM',
    isLive: false,
    streamer: 'FilmWithAlex', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=FilmWithAlex',
    videoId: 'bPuJ4JnFD1E',
    description: 'Learn cinematography fundamentals with Emmy-award winning DoP Alex Forman. Camera movement psychology, lens selection, color theory, lighting setups, and visual storytelling through composition.',
    tags: ['Film', 'Cinematography', 'Creative', 'Education'], likes: 1230,
  },
  {
    id: '12',
    title: 'Final Boss Challenge',
    category: 'Gaming',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDjcS68UoduMiAUxvUW-Emuo4P0JhZN2xu0Moe95r3qyOJOX1wuqc8LijRnB5rCdpr2zk6gmoiGpnK_4e9dwGeDhbfQkOdIBE-DIBoZrK8vazfdvFaTrkwXF8r2RDdOY48Bhl4k7LwEaijuhdYCP94zRoQjgMT7n474VIPcHKIB3E8CgW-zEYUYgjsx7zCFEtqUt97TXmhE1DQx0usG1twXHnZ7l4w95n2UOk_iESDcvEoBd8_nuNFzMY9-nNllEW8LmnHC30s4fnA',
    imageAlt: 'Epic final boss battle scene with dramatic lighting',
    time: 'In progress',
    isLive: true, viewers: 4900,
    streamer: 'BossHunter_Z', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=BossHunter',
    videoId: 'aircAruvnKk',
    description: "The ultimate gaming challenge — 12 top streamers attempt the hardest final boss fights in gaming history. Elden Ring's Malenia, Sekiro's Isshin, Cuphead's King Dice. Viewers vote live. No respawns. Pure skill.",
    tags: ['Gaming', 'Challenge', 'Boss', 'Live'], likes: 5500,
  },
  {
    id: '13',
    title: 'Acoustic Sunset Sets',
    category: 'Music',
    image: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Acoustic guitarist performing during sunset',
    time: 'Next Sunday',
    isLive: false,
    streamer: 'SunsetStrings', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SunsetStrings',
    videoId: 'wj_VEYgOzUA',
    description: 'A serene outdoor acoustic performance against a golden California sunset. Original compositions and acoustic covers. The perfect weekend unwind — raw, unprocessed music with natural reverb only the open air provides.',
    tags: ['Acoustic', 'Guitar', 'Music', 'Chill'], likes: 870,
  },
  {
    id: '14',
    title: 'The Rust Revolution',
    category: 'Tech',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Rust programming language presentation screen',
    time: 'Friday, 8:00 PM',
    isLive: false,
    streamer: 'RustLang_TV', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RustLangTV',
    videoId: 'wIyHSOugGGw',
    description: 'Why is Rust the most loved language for 8 years running? Ownership, borrowing, lifetimes, async Rust, and the new async trait stabilization. Perfect for C++ developers migrating to memory-safe systems code.',
    tags: ['Rust', 'Systems', 'Programming', 'Tech'], likes: 1650,
  },
  {
    id: '15',
    title: 'Productivity Systems Mastery',
    category: 'Workshops',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Organized workspace with notebook and planning materials',
    time: 'Dec 10, 10:00 AM',
    isLive: false,
    streamer: 'FlowStateCoach', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=FlowState',
    videoId: 'DubKbIh4jEU',
    description: 'Build a bulletproof personal productivity system from scratch. GTD methodology, time blocking, Notion/Obsidian database design, deep work principles, and the science of habit formation. Includes downloadable templates.',
    tags: ['Productivity', 'Systems', 'Notion', 'Workshop'], likes: 2100,
  },
  {
    id: '16',
    title: 'Future of Web Development 2026',
    category: 'Tech',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Laptop with diverse tech stickers and code',
    time: 'Monday next week',
    isLive: false,
    streamer: 'WebDev_Alex', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=WebDevAlex',
    videoId: 'oFRbZJXjWIA',
    description: 'Looking into the crystal ball of web technologies. From WebAssembly to AI-driven UI generation, we explore the tools and frameworks that will dominate the next few years of software engineering.',
    tags: ['Web', 'Tech', 'Future', '2026'], likes: 1200,
  },
  {
    id: '17',
    title: 'Electronic Sound Design',
    category: 'Music Production',
    image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Music producer working on a complex digital audio workstation',
    time: 'Tonight, 10 PM',
    isLive: true, viewers: 1540,
    streamer: 'SoundCrafter', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SoundCrafter',
    videoId: 'aircAruvnKk',
    description: 'Master class on creating unique sonic textures using modern hardware and soft-synths. We will build a complex atmosphere from scratch using nothing but simple sine waves and heavy processing.',
    tags: ['Music', 'Sound Design', 'Production'], likes: 890,
  },
  {
    id: '18',
    title: 'Retro Gaming Marathon',
    category: 'Gaming',
    image: 'https://images.unsplash.com/photo-1472457897821-70d3819a0e24?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Vintage arcade machines in a neon-lit room',
    time: 'Starts 1h',
    isLive: true, viewers: 2800,
    streamer: 'RetroRick', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RetroRick',
    videoId: 'jfKfPfyJRdk',
    description: 'Playing through the 100 most influential games of the 80s and 90s. Join us for a trip down memory lane, featuring perfect runs, historical trivia, and pure nostalgic bliss.',
    tags: ['Retro', 'Gaming', 'Nostalgia'], likes: 3500,
  },
  {
    id: '19',
    title: 'Minimalist Architecture Tour',
    category: 'Creative',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Modern minimalist building with sharp geometric lines',
    time: 'Dec 15, 2:00 PM',
    isLive: false,
    streamer: 'Architex', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Architex',
    videoId: ' DubKbIh4jEU',
    description: 'A virtual tour of the most striking minimalist buildings of the 21st century. We will analyze the philosophy of "Less is More" and how it translates into physical space and human experience.',
    tags: ['Architecture', 'Design', 'Minimalism'], likes: 450,
  },
  {
    id: '20',
    title: 'Python for Data Science',
    category: 'Workshops',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Digital representation of data flows and Python logo',
    time: 'Starts 3h',
    isLive: true, viewers: 3100,
    streamer: 'DataViz_Pro', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DataViz',
    videoId: 'aircAruvnKk',
    description: 'Accelerate your career with the ultimate Python for Data Science workshop. Learn Pandas, NumPy, Scikit-Learn, and how to build beautiful visualizations using Matplotlib and Seaborn.',
    tags: ['Python', 'Data Science', 'Coding'], likes: 4200,
  },
  {
    id: '21',
    title: 'Street Photography Masterclass',
    category: 'Creative',
    image: 'https://images.unsplash.com/photo-1492691523567-30730029ad0a?auto=format&fit=crop&q=80&w=800',
    imageAlt: 'Photographer capturing a rainy city street at night',
    time: 'Next Tuesday',
    isLive: false,
    streamer: 'CityLens', streamerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CityLens',
    videoId: 'wj_VEYgOzUA',
    description: 'Learn the secrets of capturing candid street moments. This masterclass covers composition, lighting, how to approach strangers, and the gear you actually need for high-quality street photography.',
    tags: ['Photography', 'Street', 'Creative'], likes: 1100,
  },
];

export const CATEGORIES = ['All Events', 'Music', 'Tech', 'Gaming', 'Workshops', 'Creative'] as const;

export const SORT_OPTIONS = [
  { value: 'popular', label: 'Sort by: Popular' },
  { value: 'newest', label: 'Sort by: Newest' },
  { value: 'upcoming', label: 'Sort by: Upcoming' },
];

